name: Ada (GNAT)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  skip-check:
    continue-on-error: false
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v4.0.0
        with:
          concurrent_skipping: same_content
          do_not_skip: '["pull_request"]'

  build:
    runs-on: ubuntu-22.04
    needs: skip-check
    if: ${{ needs.skip-check.outputs.should_skip != 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Get pip cache dir
        id: cache-dir-pip
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache Python dependencies
        uses: actions/cache@v3
        id: cache-pip
        with:
          path: ${{ steps.cache-dir-pip.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: make build
